import fs from "fs";

const courses = [
  {
    courseId: "igot-py-01",
    title: "Python for Statistical Data Analysis",
    provider: "iGOT Karmayogi (mock)",
    description: "Applied Python for official statistical systems. Vectorized pandas operations, microdata aggregation, missing data imputation, and statistical scripting for large censuses.",
    competencies: ["comp-tech-01"],
    competencyName: "Python",
    domain: "Technical",
    difficulty: "Intermediate",
    durationHours: 24,
    courseType: "Self-Paced e-Learning",
    catalogueSource: "Prototype Catalogue — iGOT-compatible mock data",
    url: "https://igotkarmayogi.gov.in/learn/python-statistical-analysis",
    active: true
  },
  {
    courseId: "igot-surv-01",
    title: "Advanced Survey Methodology",
    provider: "NSSTA (mock)",
    description: "Comprehensive formulation of socio-economic survey schedules, cognitive interviewing, questionnaire pre-testing, non-sampling error reduction, and CAPI protocols.",
    competencies: ["comp-stat-01"],
    competencyName: "Survey Design",
    domain: "Statistical",
    difficulty: "Advanced",
    durationHours: 32,
    courseType: "Blended Masterclass",
    catalogueSource: "Prototype Catalogue — iGOT-compatible mock data",
    url: "https://nssta.gov.in/courses/advanced-survey-methodology",
    active: true
  },
  {
    courseId: "igot-samp-01",
    title: "Sampling Methods for Official Statistics",
    provider: "NSSTA (mock)",
    description: "Stratified multi-stage designs, probability proportional to size (PPSWOR), Horvitz-Thompson base weight calibration, and jackknife variance estimation for national surveys.",
    competencies: ["comp-stat-02"],
    competencyName: "Sampling",
    domain: "Statistical",
    difficulty: "Advanced",
    durationHours: 28,
    courseType: "Self-Paced e-Learning",
    catalogueSource: "Prototype Catalogue — iGOT-compatible mock data",
    url: "https://nssta.gov.in/courses/sampling-methods-official-stats",
    active: true
  },
  {
    courseId: "igot-sql-01",
    title: "SQL for Government Data Systems",
    provider: "iGOT Karmayogi (mock)",
    description: "Relational database architecture for large government registries. Complex aggregations, window functions (RANK, PARTITION BY), index optimization, and administrative table joins.",
    competencies: ["comp-tech-02"],
    competencyName: "SQL",
    domain: "Technical",
    difficulty: "Intermediate",
    durationHours: 20,
    courseType: "Interactive Lab Course",
    catalogueSource: "Prototype Catalogue — iGOT-compatible mock data",
    url: "https://igotkarmayogi.gov.in/learn/sql-government-systems",
    active: true
  },
  {
    courseId: "igot-viz-01",
    title: "Data Visualization for Statistical Reporting",
    provider: "TPAC (mock)",
    description: "Visual communication principles for official data publications. Thematic choropleth mapping, district distributions, preventing distorted baselines, and accessible dashboards.",
    competencies: ["comp-tech-03"],
    competencyName: "Data Visualization",
    domain: "Technical",
    difficulty: "Foundational",
    durationHours: 16,
    courseType: "Self-Paced e-Learning",
    catalogueSource: "Prototype Catalogue — iGOT-compatible mock data",
    url: "https://tpac.gov.in/modules/data-visualization-reporting",
    active: true
  },
  {
    courseId: "igot-dq-01",
    title: "Data Quality Frameworks",
    provider: "MoSPI Internal (mock)",
    description: "Quality assurance across survey lifecycles. Designing relational consistency audit rules, outlier bounds, field fabrications checks, and validation pipelines in ASI and PLFS.",
    competencies: ["comp-stat-03"],
    competencyName: "Data Quality",
    domain: "Statistical",
    difficulty: "Intermediate",
    durationHours: 18,
    courseType: "Instructor-Led Virtual Workshop",
    catalogueSource: "Prototype Catalogue — iGOT-compatible mock data",
    url: "https://mospi.gov.in/internal/data-quality-frameworks",
    active: true
  },
  {
    courseId: "igot-gis-01",
    title: "GIS for Official Statistics",
    provider: "TPAC (mock)",
    description: "Geographic Information Systems for sampling frames. Delineating primary sampling units (PSUs) using satellite imagery, ward shapefiles, and spatial data integration.",
    competencies: ["comp-tech-04"],
    competencyName: "GIS",
    domain: "Technical",
    difficulty: "Intermediate",
    durationHours: 22,
    courseType: "Hands-on Workshop",
    catalogueSource: "Prototype Catalogue — iGOT-compatible mock data",
    url: "https://tpac.gov.in/modules/gis-official-statistics",
    active: true
  },
  {
    courseId: "igot-ai-01",
    title: "Introduction to AI for Government",
    provider: "iGOT Karmayogi (mock)",
    description: "Foundational machine learning concepts for civil services. Automated missing value imputation, record linkage across administrative databases, and synthetic data generation.",
    competencies: ["comp-tech-05"],
    competencyName: "AI/ML",
    domain: "Technical",
    difficulty: "Foundational",
    durationHours: 16,
    courseType: "Self-Paced e-Learning",
    catalogueSource: "Prototype Catalogue — iGOT-compatible mock data",
    url: "https://igotkarmayogi.gov.in/learn/ai-for-government",
    active: true
  },
  {
    courseId: "igot-dp-01",
    title: "Data Privacy for Government Officials",
    provider: "iGOT Karmayogi (mock)",
    description: "Operationalizing the Digital Personal Data Protection (DPDP) Act 2023. De-identification protocols, k-anonymity, differential privacy, and preventing microdata linkage attacks.",
    competencies: ["comp-gov-01"],
    competencyName: "Data Privacy",
    domain: "Digital Governance",
    difficulty: "Advanced",
    durationHours: 18,
    courseType: "Self-Paced e-Learning",
    catalogueSource: "Prototype Catalogue — iGOT-compatible mock data",
    url: "https://igotkarmayogi.gov.in/learn/dpdp-act-official-data",
    active: true
  },
  {
    courseId: "igot-cs-01",
    title: "Cybersecurity Fundamentals",
    provider: "TPAC (mock)",
    description: "Protecting government statistical infrastructure. TLS 1.3 cryptographic protocols, role-based access control (RBAC), CERT-In security guidelines, and secure CAPI tablet transmission.",
    competencies: ["comp-gov-02"],
    competencyName: "Cybersecurity",
    domain: "Digital Governance",
    difficulty: "Intermediate",
    durationHours: 14,
    courseType: "Self-Paced e-Learning",
    catalogueSource: "Prototype Catalogue — iGOT-compatible mock data",
    url: "https://tpac.gov.in/modules/cybersecurity-fundamentals",
    active: true
  },
  {
    courseId: "igot-sdg-01",
    title: "Official Statistics and SDG Indicators",
    provider: "MoSPI Internal (mock)",
    description: "Methodology of the National Indicator Framework (NIF) for Sustainable Development Goals (SDGs). Monitoring tier-I and tier-II indicators across central ministries.",
    competencies: ["comp-stat-04"],
    competencyName: "Official Statistics",
    domain: "Statistical",
    difficulty: "Intermediate",
    durationHours: 20,
    courseType: "Self-Paced e-Learning",
    catalogueSource: "Prototype Catalogue — iGOT-compatible mock data",
    url: "https://mospi.gov.in/internal/sdg-indicators-nif",
    active: true
  },
  {
    courseId: "igot-na-01",
    title: "National Accounts Fundamentals",
    provider: "NSSTA (mock)",
    description: "Concepts of the UN System of National Accounts (SNA 2008). GDP compilation, Gross Value Added (GVA) at basic prices, production and expenditure approaches, and index deflators.",
    competencies: ["comp-stat-04"],
    competencyName: "Official Statistics",
    domain: "Statistical",
    difficulty: "Advanced",
    durationHours: 26,
    courseType: "Blended Seminar",
    catalogueSource: "Prototype Catalogue — iGOT-compatible mock data",
    url: "https://nssta.gov.in/courses/national-accounts-fundamentals",
    active: true
  },
  {
    courseId: "igot-labour-01",
    title: "Labour Statistics",
    provider: "MoSPI Internal (mock)",
    description: "Concepts and definitions in Periodic Labour Force Surveys. Usual Principal & Subsidiary Status (UPSS), Current Weekly Status (CWS), labour force participation rates, and worker-population ratios.",
    competencies: ["comp-stat-01", "comp-stat-04"],
    competencyName: "Survey Design",
    domain: "Statistical",
    difficulty: "Intermediate",
    durationHours: 16,
    courseType: "Self-Paced e-Learning",
    catalogueSource: "Prototype Catalogue — iGOT-compatible mock data",
    url: "https://mospi.gov.in/internal/labour-statistics-plfs",
    active: true
  },
  {
    courseId: "igot-agri-01",
    title: "Agricultural Statistics",
    provider: "NSSTA (mock)",
    description: "Methodologies for crop cutting experiments, Timely Reporting Scheme (TRS), Establishment of an Agency for Reporting Agricultural Statistics (EARAS), and agricultural census sampling.",
    competencies: ["comp-stat-02", "comp-stat-03"],
    competencyName: "Sampling",
    domain: "Statistical",
    difficulty: "Intermediate",
    durationHours: 18,
    courseType: "Self-Paced e-Learning",
    catalogueSource: "Prototype Catalogue — iGOT-compatible mock data",
    url: "https://nssta.gov.in/courses/agricultural-statistics-methodology",
    active: true
  },
  {
    courseId: "igot-pm-01",
    title: "Project Management for Government Officers",
    provider: "iGOT Karmayogi (mock)",
    description: "Managing timelines, multi-state field enumerator teams, logistics planning, CAPI synchronization checkpoints, and quality milestones for nationwide survey rounds.",
    competencies: ["comp-mgt-05"],
    competencyName: "Project Management",
    domain: "Behavioural & Managerial",
    difficulty: "Intermediate",
    durationHours: 20,
    courseType: "Self-Paced e-Learning",
    catalogueSource: "Prototype Catalogue — iGOT-compatible mock data",
    url: "https://igotkarmayogi.gov.in/learn/project-management-government",
    active: true
  },
  {
    courseId: "igot-eth-01",
    title: "Ethics and Objectivity in National Statistical Reporting",
    provider: "NSSTA (mock)",
    description: "UN Fundamental Principles of Official Statistics. Impartiality, professional independence, transparent revision metadata, and adhering strictly to pre-announced release calendars.",
    competencies: ["comp-mgt-03"],
    competencyName: "Ethics",
    domain: "Behavioural & Managerial",
    difficulty: "Foundational",
    durationHours: 12,
    courseType: "Self-Paced e-Learning",
    catalogueSource: "Prototype Catalogue — iGOT-compatible mock data",
    url: "https://nssta.gov.in/courses/statistical-ethics-objectivity",
    active: true
  },
  {
    courseId: "igot-comm-01",
    title: "Statistical Briefing and Public Communication",
    provider: "TPAC (mock)",
    description: "Techniques for translating econometric uncertainty, margins of error, and confidence intervals into clear, non-technical policy briefs for administrative ministries and media.",
    competencies: ["comp-mgt-01"],
    competencyName: "Communication",
    domain: "Behavioural & Managerial",
    difficulty: "Intermediate",
    durationHours: 14,
    courseType: "Interactive Workshop",
    catalogueSource: "Prototype Catalogue — iGOT-compatible mock data",
    url: "https://tpac.gov.in/modules/statistical-communication-briefs",
    active: true
  }
];

const fileContent = `// Prototype Catalogue — iGOT-compatible mock data
// Smart India Hackathon Problem Statement 26101

export const PROTOTYPE_CATALOGUE_DISCLAIMER = "Prototype Catalogue — iGOT-compatible mock data";

export const IGOT_COURSE_CATALOGUE = ${JSON.stringify(courses, null, 2)};
`;

fs.writeFileSync("src/data/igotCoursesCatalogue.js", fileContent, "utf8");
fs.writeFileSync("server/data/igotCoursesCatalogue.js", fileContent, "utf8");
console.log(`Generated ${courses.length} courses in src/ and server/`);
