import React, { createContext, useContext, useState, useEffect } from "react";

const LanguageContext = createContext();

export const translations = {
  en: {
    // Branding & Header
    govMasthead: "Government of India | Ministry of Statistics and Programme Implementation (MoSPI)",
    govMastheadSih: "Smart India Hackathon (PS: 26101)",
    govMastheadNssta: "National Statistical Systems Training Academy (NSSTA)",
    appTitle: "StatSkill AI",
    appSubtitle: "Competency Intelligence & Personalized Learning Platform",
    officialSystem: "India's Official Statistical System (MoSPI)",
    officialCadre: "Official Statistical Cadre",
    mospiCadre: "MoSPI Subordinate Statistical Service",
    logout: "Logout",
    guest: "Guest",
    officer: "Officer",
    trainer: "Trainer",
    statisticalOfficer: "Statistical Officer",
    seniorAnalyst: "Senior Statistical Analyst",
    authorizedFaculty: "Authorized Faculty",
    activeCadre: "ACTIVE CADRE",
    welcome: "Welcome",
    designationLabel: "Designation",
    careerTargetLabel: "Career Milestone Target",
    takeDiagnosticBtn: "Take Diagnostic (MEASURE)",

    // Navigation Tabs
    dashboard: "Dashboard",
    officerProfile: "Officer Profile",
    assessment: "Assessment",
    skillGaps: "Skill Gaps",
    recommendations: "Recommendations",
    learning: "Learning",
    practiceQuiz: "Practice Quiz",
    aiAssistant: "AI Assistant",
    progress: "Progress",
    uploadMaterial: "Upload Material",
    aiMcqGenerator: "AI MCQ Generator",
    questionReview: "Question Review",
    questionBank: "Question Bank",
    learnerPerformance: "Learner Performance",

    // Stat Cards
    overallCompetencyScore: "Overall Competency Score",
    targetRoleBenchmark: "Target Role Benchmark: 85%",
    trendQuarter: "+6% this quarter",
    assessedCompetencies: "Assessed Competencies",
    pendingDiagnostics: "3 Pending Diagnostics",
    highPriorityGaps: "High Priority Gaps",
    requiresImmediateAction: "Requires Immediate Action",
    learningProgress: "Learning Progress",
    coursesActive: "Courses Active",

    // Dashboard Sections
    competencyRadarAnalysis: "Competency Radar Analysis",
    radarSubtitle: "Current Proficiency vs. Senior Statistical Analyst Target (Scale 1-5)",
    radarCurrentProficiency: "Current Proficiency (1-5)",
    radarTargetRole: "Target (Senior Statistical Analyst)",
    viewFullMatrix: "View Full Matrix",
    prioritySkillGapsTitle: "Priority Skill Gaps (DIAGNOSE)",
    viewAll: "View All",
    needAiDiagnostic: "Need an AI Diagnostic Evaluation?",
    generatePsychometric: "Generate full psychometric analysis via Gemini Interactions API",
    diagnoseBtn: "Diagnose",
    aiRecommendedLearning: "AI-Recommended Learning Paths (LEARN)",
    curatedGapsSubtitle: "Curated specifically to address identified gaps for Senior Statistical Analyst role",
    exploreCatalog: "Explore Catalog",
    activityTimeline: "Recent Competency Improvement & Activity",
    activitySubtitle: "Real-time log of assessment calibration, quiz score updates, and learning progress",
    calibration: "Calibration",
    upgradedFrom: "Upgraded from Level",
    to: "to",
    via: "via",
    enrolledCourse: "Enrolled Course",
    currentLabel: "Current",
    targetLabel: "Target",
    requiredLabel: "Required",
    deficiencyLabel: "Deficiency",
    meetsRequirement: "Meets Requirement",
    bridgeGapBtn: "Bridge Gap",
    startLearningBtn: "Start Learning",
    enrollBtn: "Enroll on iGOT (Mock)",
    continueLearningBtn: "Continue Learning",
    matchScore: "Match Score",
    providerLabel: "Provider",
    competencyLabel: "Competency",
    gapLabel: "Gap",
    whyRecommended: "Why this was recommended",
    durationLabel: "Hours Duration",
    selfPaced: "Self-Paced",

    // Competency Loop Steps
    competencyGrowthLoop: "Competency Growth Loop",
    loopMeasure: "Measure",
    loopDiagnose: "Diagnose",
    loopLearn: "Learn",
    loopReassess: "Reassess",
    step1Measure: "Step 1 in Core Competency Loop: MEASURE",
    step2Diagnose: "Step 2 in Core Competency Loop: DIAGNOSE",
    step3Learn: "Step 3 in Core Competency Loop: LEARN",
    step4Reassess: "Step 4 in Core Competency Loop: REASSESS",
    trainerConsole: "Trainer Authority Console",

    // Domains
    domainStatistical: "Statistical Methodology",
    domainTechnical: "Technical & Computation",
    domainGovernance: "Digital Governance & Data Privacy",
    domainBehavioural: "Behavioural & Leadership",
    "Statistical": "Statistical",
    "Technical": "Technical",
    "Digital Governance": "Digital Governance",
    "Behavioural & Managerial": "Behavioural & Managerial",
    "ALL": "ALL",

    // Competencies
    "Survey Design": "Survey Design",
    "Sampling Methods & Survey Design": "Sampling Methods & Survey Design",
    "Sampling": "Sampling Methods & Frame Selection",
    "Official Statistics": "Official Statistical Systems (NSSO, ASI, PLFS)",
    "Official Stats": "Official Statistics",
    "Data Quality": "Data Quality, Validation & Microdata Scrubbing",
    "Data Quality & Validation": "Data Quality, Validation & Microdata Scrubbing",
    "Python": "Python for Statistical Analysis",
    "Python for Statistical Analysis": "Python for Statistical Analysis",
    "SQL": "SQL Database Querying & Enterprise Warehousing",
    "SQL Databases": "SQL Database Querying & Enterprise Warehousing",
    "AI/ML": "AI/ML for Statistical Modeling",
    "AI/ML for Statistical Modeling": "AI/ML for Statistical Modeling",
    "Data Visualization": "Data Visualization & Dashboard Analytics",
    "Data Visualization & Dashboard Analytics": "Data Visualization & Dashboard Analytics",
    "Data Privacy": "DPDP Act 2023 & Microdata Anonymization",
    "DPDP Act & Data Privacy": "DPDP Act 2023 & Microdata Anonymization",
    "Cybersecurity": "Cybersecurity & CERT-In Protocol",
    "Cybersecurity & CERT-In Protocol": "Cybersecurity & CERT-In Protocol",
    "Ethics": "Statistical Ethics & Objectivity",
    "Statistical Ethics & Objectivity": "Statistical Ethics & Objectivity",
    "Project Mgmt": "Administrative Communication & Project Management",
    "Administrative Communication & Project Management": "Administrative Communication & Project Management",
    "Communication": "Administrative Communication & Reporting",
    "Administrative Communication & Reporting": "Administrative Communication & Reporting",
    "Microdata Anonymization": "Microdata Anonymization",
    "Time Series Forecasting": "Time Series Forecasting",
    "National Accounts Statistics": "National Accounts Statistics",

    // Designations
    "Statistical Officer": "Statistical Officer",
    "Senior Statistical Analyst": "Senior Statistical Analyst",
    "Junior Statistical Officer": "Junior Statistical Officer",
    "Assistant Director": "Assistant Director",
    "Deputy Director": "Deputy Director",
    "Joint Director": "Joint Director",
    "Director": "Director",
    "Director General": "Director General",
    "Senior Adviser": "Senior Adviser",
    "Chief Statistician of India": "Chief Statistician of India",
    "Ananya Sharma": "Ananya Sharma",

    // Priorities & Badges
    priorityMeets: "Meets Requirement",
    priorityLow: "Low Priority (1-10)",
    priorityMedium: "Medium Priority (11-25)",
    priorityHigh: "High Priority (26-50)",
    priorityCritical: "Critical Priority (51+)",
    CRITICAL: "CRITICAL",
    HIGH: "HIGH",
    MEDIUM: "MEDIUM",
    LOW: "LOW",
    MEETS_REQUIREMENT: "MEETS REQUIREMENT",
    COMPLETED: "COMPLETED",
    IN_PROGRESS: "IN PROGRESS",
    NOT_STARTED: "NOT STARTED",
    RECOMMENDED: "RECOMMENDED",
    ENROLLED: "ENROLLED",

    // Trainer Module Keys
    nsstaFacultyConsole: "NSSTA Faculty Console",
    statisticalCapacityOversight: "National Statistical Capacity Oversight",
    supervisingBatch: "Supervising Statistical Officer Cohort Batch 2024-26",
    enrolledCadreOfficers: "4 Enrolled Cadre Officers",
    cohortOfficers: "Cohort Officers",
    allActiveCadre: "All Active in SSS Cadre",
    batchAverageScore: "Batch Average Score",
    benchmarkLabel: "Benchmark: 80%",
    trendMonth: "+4% this month",
    uploadedMaterials: "Uploaded Materials",
    handbooksIngested: "Handbooks Ingested",
    verifiedQuestions: "Verified Questions",
    pendingReview: "Pending Review",
    cohortPerformanceTitle: "Statistical Officers Cohort Performance",
    viewFullAnalytics: "View Full Analytics",
    questionPipelineTitle: "Question Bank & Ingestion Pipeline",
    approvedQuestionsInBank: "Approved Questions in Bank",
    pendingGeneratedItems: "Pending Generated Items",
    ingestMaterialPrompt: "Upload official training manuals, NSS survey guidelines, and statistical methodology handbooks to generate calibrated assessment items using Gemini Interactions API.",
    manageBankPrompt: "Review, approve, and refine AI-generated questions before publishing them to the official cadre question bank.",
    uploadMaterialNow: "Upload Material Now",
    openQuestionBank: "Open Question Bank",
    dragDropManuals: "Drag and drop training manuals or click to browse",
    supportedFormats: "Supports TXT, PDF, DOCX (Max 20MB per file)",
    presetManualsTitle: "Or Select Official MoSPI Preset Training Material:",
    customManualText: "Or Paste Manual Excerpt / Training Text Directly:",
    ingestAndGenerate: "Ingest Material & Proceed to MCQ Generator",
    mcqConfigTitle: "AI MCQ Synthesis Configuration",
    selectDomainPrompt: "Select Target Competency Domain:",
    selectCompPrompt: "Select Target Competency:",
    selectDifficultyPrompt: "Select Difficulty Level:",
    selectQuestionCount: "Number of Questions to Generate:",
    foundationalDiff: "Foundational (Level 1-2)",
    intermediateDiff: "Intermediate (Level 3)",
    advancedDiff: "Advanced (Level 4-5)",
    generateWithGemini: "Generate MCQs using Gemini Interactions API",
    generatingMcqsWait: "Synthesizing Cadre Assessment Items with Gemini AI...",
    reviewTitle: "Trainer Assessment Item Review & Verification",
    reviewSubtitle: "Inspect AI-generated assessment items, verify ground-truth source citations, and approve for the official Cadre Question Bank.",
    approveAll: "Approve All Verified Items",
    approveSelected: "Approve Question",
    rejectSelected: "Reject / Discard",
    editQuestion: "Edit Question Content",
    questionStem: "Question Stem / Text",
    optionsLabel: "Options",
    correctAnswerIndex: "Correct Answer (Index)",
    explanationLabel: "Psychometric / Methodological Explanation",
    sourceCitation: "Grounding Manual Citation",
    saveAndApprove: "Save & Publish to Question Bank",
    questionBankTitle: "Official Assessment Repository & Question Bank",
    questionBankSubtitle: "Archived psychometric and technical questions generated from official training material and validated by NSSTA trainers.",
    searchQuestionsPlaceholder: "Search questions, competencies, source manuals...",
    allDifficulties: "All Difficulties",
    allDomains: "All Domains",
    exportJson: "Export JSON",
    ingestNewMaterial: "Ingest New Material",
    noQuestionsFound: "No Assessment Items Found",
    noQuestionsHint: "Try adjusting your search criteria, or upload a training document to generate fresh assessment items.",
    viewOptionsCitation: "View Options & Source Excerpt →",
    learnerPerformanceTitle: "Learner Competency & Capacity Monitoring",
    learnerPerformanceSubtitle: "Comprehensive psychometric and technical performance tracking across all enrolled statistical officers.",
    enrolledOfficersList: "Enrolled Statistical Officers (Batch 2024-26)",
    individualCadreDossier: "Individual Cadre Dossier",
    domainProficiencyBreakdown: "Domain Proficiency Breakdown",
    facultyRecommendedAction: "Faculty Recommended Action",
    facultyActionDesc: "Recommend enrolment in NSSTA AI Imputation module and DPDP Act compliance track to resolve top priority gaps.",
    selectOfficerToInspect: "Select an officer to inspect their cadre dossier.",

    // Officer Dashboard & Realtime Beacon Keys
    liveCadreBeacon: "Live Cadre Synchronization Active",
    cadreBeaconDesc: "Synchronized with NSSTA Subordinate Statistical Service competency benchmark matrix (v2026.2).",
    simulationTitle: "What-If Cadre Benchmark Simulation",
    simulationDesc: "Adjust target standard to project required capacity building for upcoming cadre promotion rounds:",
    targetStandard: "Target Standard",
    promotionThreshold: "Promotion Threshold (85%)",
    goodMorning: "Good morning",
    goodAfternoon: "Good afternoon",
    goodEvening: "Good evening",
    profileOverview: "Official Cadre Dossier & APAR Competency Profile",

    // Step Navigator & MCQ Generator Keys
    step1UploadNav: "1. Upload & Ingest",
    step2GenerateNav: "2. AI Generation",
    step3ReviewNav: "3. Review & Validate",
    step2McqEngine: "Step 2: AI MCQ Formulation Engine",
    groundedAssessmentGen: "Grounded Assessment Generation with Gemini",
    strictlyGrounded: "Strictly grounded question formulation from",
    changeMaterial: "← Change Material",
    generationParams: "Generation Parameters",
    wordsParsed: "words",
    charsParsed: "chars parsed",
    numQuestionsFormulate: "Number of Questions to Formulate",
    rapidCheck: "5 Questions (Rapid Check)",
    standardBatch: "10 Questions (Standard Batch - Recommended)",
    comprehensiveDiag: "15 Questions (Comprehensive Diagnostic)",
    targetDomainHint: "Target Domain Hint",
    competencyAlignment: "Competency Alignment",
    strictGroundingGuardrails: "Strict Grounding & Anti-Hallucination Guardrails",
    verifiableTextExcerpt: "Verifiable text excerpt for every question",
    zeroInventedFacts: "Zero invented facts / Zero duplicate items",
    chunkingText: "Chunking text...",
    runningGeminiApi: "Running Gemini AI Interactions API...",
    verifyingSourceExcerpts: "Verifying source excerpts & JSON schema...",
    generateQuestionsBtn: "Generate Questions with Gemini",

    // Question Review Keys
    step3Review: "Step 3: Trainer Review & Provenance Audit",
    validateCurateTitle: "Validate & Curate Generated Assessment MCQs",
    trainingDocument: "Training Document",
    sourceReviewAudit: "Review source citations and approve for the official Question Bank.",
    approveAllBtn: "Approve All",
    publishToBankBtn: "Publish Approved to Bank",
    savingWait: "Saving...",
    successPublishedBank: "Successfully Published to Question Bank!",
    archivedInFirestore: "assessment items have been archived in Firestore and are now available for cadre diagnostic assessments.",
    ingestAnotherFile: "Ingest Another File",
    totalGenerated: "Total Generated",
    approved: "Approved",
    pending: "Pending",
    rejected: "Rejected",
    allQuestions: "All Questions",
    pendingReviewFilter: "Pending Review",
    approvedFilter: "Approved",
    rejectedFilter: "Rejected",
    questionNumber: "Question",
    editBtn: "Edit",
    approveBtn: "Approve",
    rejectBtn: "Reject",
    sourceExcerptCitation: "Source Grounding Excerpt (Verbatim Citation from Document)",
    officialExplanation: "Official Explanation",
    editAssessmentQuestion: "Edit Assessment Question",
    questionText: "Question Text",
    optionsSelectRadio: "Options (Select radio for correct answer)",
    difficulty: "Difficulty",
    saveMarkEdited: "Save & Mark Edited",

    // Assessment Page Keys
    latestCompletedDiag: "Latest Completed Diagnostic",
    score: "Score",
    of: "of",
    correct: "Correct",
    completedOn: "Completed on",
    printPdfReport: "Print PDF Report",
    viewFullBreakdown: "View Full Breakdown",
    officialCertInstrument: "Official Certification Instrument",
    mospiNsstaStandard: "MoSPI / NSSTA Standardized Specification",
    nationalCadreDiagEngine: "National Statistical Cadre Competency Diagnostic Engine",
    deterministicBenchmarking: "Deterministic psychometric benchmarking across Statistical, Technical, Digital Governance, and Behavioural domains.",
    minutes: "Minutes",
    questions: "Questions",
    dimensionsEvaluated: "11 Competency Dimensions Evaluated in this Diagnostic",

    // Actions & Common
    printReport: "Print / Save PDF",
    exportReport: "Export Official Diagnostic Report (PDF / Print)",
    retakeDiagnostic: "Retake Diagnostic",
    viewSkillGaps: "View Updated Skill Gaps",
    exploreCourses: "Explore Recommended Courses",
    startDiagnostic: "Start 22-Question Diagnostic Now",
    send: "Send",
    retry: "Retry",
    editProfile: "Edit Profile",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    listening: "Listening... Speak your statistical question now",
    speakQuery: "Speak query (Speech-to-Text)",
    stopListening: "Stop Listening"
  },
  hi: {
    // Branding & Header
    govMasthead: "भारत सरकार | सांख्यिकी एवं कार्यक्रम कार्यान्वयन मंत्रालय (MoSPI)",
    govMastheadSih: "स्मार्ट इंडिया हैकथॉन (PS: 26101)",
    govMastheadNssta: "राष्ट्रीय सांख्यिकी प्रणाली प्रशिक्षण अकादमी (NSSTA)",
    appTitle: "स्टेटस्किल एआई",
    appSubtitle: "दक्षता विश्लेषण एवं व्यक्तिगत शिक्षण मंच",
    officialSystem: "भारतीय आधिकारिक सांख्यिकी प्रणाली (MoSPI)",
    officialCadre: "आधिकारिक सांख्यिकी संवर्ग",
    mospiCadre: "MoSPI अधीनस्थ सांख्यिकी सेवा",
    logout: "लॉग आउट",
    guest: "अतिथि",
    officer: "अधिकारी",
    trainer: "प्रशिक्षक",
    statisticalOfficer: "सांख्यिकी अधिकारी",
    seniorAnalyst: "वरिष्ठ सांख्यिकी विश्लेषक",
    authorizedFaculty: "अधिकृत संकाय",
    activeCadre: "सक्रिय संवर्ग",
    welcome: "स्वागत है",
    designationLabel: "पदनाम",
    careerTargetLabel: "करियर लक्ष्य",
    takeDiagnosticBtn: "मूल्यांकन दें (मापें)",

    // Navigation Tabs
    dashboard: "डैशबोर्ड",
    officerProfile: "अधिकारी प्रोफाइल",
    assessment: "दक्षता मूल्यांकन",
    skillGaps: "कौशल अंतराल",
    recommendations: "अनुशंसाएं",
    learning: "अध्ययन एवं पाठ्यक्रम",
    practiceQuiz: "अभ्यास प्रश्नोत्तरी",
    aiAssistant: "एआई सहायक",
    progress: "प्रगति एवं विकास",
    uploadMaterial: "प्रशिक्षण सामग्री अपलोड",
    aiMcqGenerator: "एआई प्रश्न निर्माता",
    questionReview: "प्रश्न समीक्षा",
    questionBank: "प्रश्न बैंक",
    learnerPerformance: "प्रशिक्षार्थी प्रदर्शन",

    // Stat Cards
    overallCompetencyScore: "समग्र दक्षता स्कोर",
    targetRoleBenchmark: "लक्ष्य संवर्ग मानक: 85%",
    trendQuarter: "इस तिमाही +6%",
    assessedCompetencies: "मूल्यांकित दक्षताएँ",
    pendingDiagnostics: "3 शेष मूल्यांकन",
    highPriorityGaps: "उच्च प्राथमिकता अंतराल",
    requiresImmediateAction: "तत्काल कार्रवाई आवश्यक",
    learningProgress: "अध्ययन प्रगति",
    coursesActive: "सक्रिय पाठ्यक्रम",

    // Dashboard Sections
    competencyRadarAnalysis: "दक्षता रडार विश्लेषण",
    radarSubtitle: "वर्तमान प्रवीणता बनाम वरिष्ठ सांख्यिकी विश्लेषक लक्ष्य (पैमाना 1-5)",
    radarCurrentProficiency: "वर्तमान प्रवीणता (1-5)",
    radarTargetRole: "लक्ष्य (वरिष्ठ सांख्यिकी विश्लेषक)",
    viewFullMatrix: "संपूर्ण मैट्रिक्स देखें",
    prioritySkillGapsTitle: "प्राथमिकता कौशल अंतराल (निदान)",
    viewAll: "सभी देखें",
    needAiDiagnostic: "एआई दक्षता विश्लेषण आवश्यक है?",
    generatePsychometric: "जेमिनी इंटरैक्शन एपीआई द्वारा पूर्ण विश्लेषण उत्पन्न करें",
    diagnoseBtn: "निदान करें",
    aiRecommendedLearning: "एआई-अनुशंसित अध्ययन पथ (सीखें)",
    curatedGapsSubtitle: "वरिष्ठ सांख्यिकी विश्लेषक पद के अंतराल को पाटने हेतु तैयार",
    exploreCatalog: "कैटलॉग देखें",
    activityTimeline: "दक्षता संवर्धन एवं गतिविधि इतिहास",
    activitySubtitle: "मूल्यांकन अंशांकन, प्रश्नोत्तरी स्कोर और अध्ययन प्रगति का वास्तविक समय लॉग",
    calibration: "अंशांकन",
    upgradedFrom: "स्तर से उन्नत",
    to: "से",
    via: "द्वारा",
    enrolledCourse: "नामांकित पाठ्यक्रम",
    currentLabel: "वर्तमान",
    targetLabel: "लक्ष्य",
    requiredLabel: "अपेक्षित",
    deficiencyLabel: "कमी",
    meetsRequirement: "आवश्यकता पूर्ण",
    bridgeGapBtn: "अंतर पाटें",
    startLearningBtn: "अध्ययन प्रारंभ करें",
    enrollBtn: "iGOT पर नामांकन करें (मॉक)",
    continueLearningBtn: "अध्ययन जारी रखें",
    matchScore: "मैच स्कोर",
    providerLabel: "प्रदाता",
    competencyLabel: "दक्षता",
    gapLabel: "कमी",
    whyRecommended: "यह अनुशंसा क्यों की गई",
    durationLabel: "घंटे की अवधि",
    selfPaced: "स्व-गति",

    // Competency Loop Steps
    competencyGrowthLoop: "दक्षता संवर्धन चक्र",
    loopMeasure: "मापें",
    loopDiagnose: "निदान",
    loopLearn: "सीखें",
    loopReassess: "पुनर्मूल्यांकन",
    step1Measure: "दक्षता चक्र चरण 1: मापें (MEASURE)",
    step2Diagnose: "दक्षता चक्र चरण 2: निदान (DIAGNOSE)",
    step3Learn: "दक्षता चक्र चरण 3: सीखें (LEARN)",
    step4Reassess: "दक्षता चक्र चरण 4: पुनर्मूल्यांकन (REASSESS)",
    trainerConsole: "प्रशिक्षक प्राधिकरण कंसोल",

    // Domains
    domainStatistical: "सांख्यिकीय कार्यप्रणाली",
    domainTechnical: "तकनीकी एवं संगणना",
    domainGovernance: "डिजिटल शासन एवं डेटा गोपनीयता",
    domainBehavioural: "व्यवहार एवं नेतृत्व क्षमता",
    "Statistical": "सांख्यिकीय",
    "Technical": "तकनीकी",
    "Digital Governance": "डिजिटल शासन",
    "Behavioural & Managerial": "व्यवहार एवं प्रबंधन",
    "ALL": "सभी",

    // Competencies
    "Survey Design": "सर्वेक्षण प्रारूप",
    "Sampling Methods & Survey Design": "प्रतिचयन विधियां एवं सर्वेक्षण प्रारूप",
    "Sampling": "प्रतिचयन विधियां एवं फ्रेम चयन",
    "Official Statistics": "आधिकारिक सांख्यिकी प्रणाली (NSSO, ASI, PLFS)",
    "Official Stats": "आधिकारिक सांख्यिकी",
    "Data Quality": "डेटा गुणवत्ता एवं माइक्रोडाटा शोधन",
    "Data Quality & Validation": "डेटा गुणवत्ता एवं सत्यापन",
    "Python": "पायथन सांख्यिकीय विश्लेषण",
    "Python for Statistical Analysis": "सांख्यिकीय विश्लेषण हेतु पायथन",
    "SQL": "एसक्यूएल डेटाबेस एवं वेयरहाउसिंग",
    "SQL Databases": "एसक्यूएल डेटाबेस क्वेरी",
    "AI/ML": "सांख्यिकी हेतु एआई/एमएल",
    "AI/ML for Statistical Modeling": "सांख्यिकीय मॉडलिंग हेतु एआई/एमएल",
    "Data Visualization": "डेटा विज़ुअलाइज़ेशन एवं एनालिटिक्स",
    "Data Visualization & Dashboard Analytics": "डेटा विज़ुअलाइज़ेशन एवं डैशबोर्ड एनालिटिक्स",
    "Data Privacy": "डीपीडीपी अधिनियम 2023 एवं गोपनीयता",
    "DPDP Act & Data Privacy": "डीपीडीपी अधिनियम एवं डेटा गोपनीयता",
    "Cybersecurity": "साइबर सुरक्षा एवं सीईआरटी-इन",
    "Cybersecurity & CERT-In Protocol": "साइबर सुरक्षा एवं सीईआरटी-इन प्रोटोकॉल",
    "Ethics": "सांख्यिकीय नैतिकता एवं निष्पक्षता",
    "Statistical Ethics & Objectivity": "सांख्यिकीय नैतिकता एवं निष्पक्षता",
    "Project Mgmt": "प्रशासनिक संप्रेषण एवं प्रबंधन",
    "Administrative Communication & Project Management": "प्रशासनिक संप्रेषण एवं परियोजना प्रबंधन",
    "Communication": "प्रशासनिक संप्रेषण एवं रिपोर्टिंग",
    "Administrative Communication & Reporting": "प्रशासनिक संप्रेषण एवं रिपोर्टिंग",
    "Microdata Anonymization": "माइक्रोडाटा अनामीकरण",
    "Time Series Forecasting": "समय श्रृंखला पूर्वानुमान",
    "National Accounts Statistics": "राष्ट्रीय लेखा सांख्यिकी",

    // Designations
    "Statistical Officer": "सांख्यिकी अधिकारी",
    "Senior Statistical Analyst": "वरिष्ठ सांख्यिकी विश्लेषक",
    "Junior Statistical Officer": "कनिष्ठ सांख्यिकी अधिकारी",
    "Assistant Director": "सहायक निदेशक",
    "Deputy Director": "उप निदेशक",
    "Joint Director": "संयुक्त निदेशक",
    "Director": "निदेशक",
    "Director General": "महानिदेशक",
    "Senior Adviser": "वरिष्ठ सलाहकार",
    "Chief Statistician of India": "भारत के मुख्य सांख्यिकीविद्",
    "Ananya Sharma": "अनन्या शर्मा",

    // Priorities & Badges
    priorityMeets: "आवश्यकता पूर्ण",
    priorityLow: "अल्प प्राथमिकता (1-10)",
    priorityMedium: "मध्यम प्राथमिकता (11-25)",
    priorityHigh: "उच्च प्राथमिकता (26-50)",
    priorityCritical: "अति महत्वपूर्ण प्राथमिकता (51+)",
    CRITICAL: "अति महत्वपूर्ण",
    HIGH: "उच्च",
    MEDIUM: "मध्यम",
    LOW: "अल्प",
    MEETS_REQUIREMENT: "आवश्यकता पूर्ण",
    COMPLETED: "पूर्ण",
    IN_PROGRESS: "प्रगति पर",
    NOT_STARTED: "शुरू नहीं हुआ",
    RECOMMENDED: "अनुशंसित",
    ENROLLED: "नामांकित",

    // Trainer Module Keys
    nsstaFacultyConsole: "एनएसएसटीए संकाय कंसोल",
    statisticalCapacityOversight: "राष्ट्रीय सांख्यिकी क्षमता निगरानी",
    supervisingBatch: "सांख्यिकी अधिकारी बैच 2024-26 का पर्यवेक्षण",
    enrolledCadreOfficers: "4 नामांकित संवर्ग अधिकारी",
    cohortOfficers: "बैच के अधिकारी",
    allActiveCadre: "अधीनस्थ सांख्यिकी सेवा में सक्रिय",
    batchAverageScore: "बैच का औसत स्कोर",
    benchmarkLabel: "संवर्ग मानक: 80%",
    trendMonth: "इस माह +4%",
    uploadedMaterials: "अपलोड की गई सामग्री",
    handbooksIngested: "3 नियमावली प्रविष्ट",
    verifiedQuestions: "सत्यापित प्रश्न बैंक",
    pendingReview: "समीक्षा हेतु शेष",
    cohortPerformanceTitle: "सांख्यिकी अधिकारी बैच का समग्र प्रदर्शन",
    viewFullAnalytics: "संपूर्ण विश्लेषण देखें",
    questionPipelineTitle: "प्रश्न बैंक एवं निर्माण पाइपलाइन",
    approvedQuestionsInBank: "बैंक में स्वीकृत प्रश्न",
    pendingGeneratedItems: "समीक्षा हेतु लंबित प्रश्न",
    ingestMaterialPrompt: "जेमिनी इंटरैक्शन एपीआई द्वारा आधिकारिक सर्वेक्षण नियमावली और सांख्यिकी पुस्तकों से नए बहुविकल्पीय प्रश्न बनाएं।",
    manageBankPrompt: "आधिकारिक संवर्ग प्रश्न बैंक में जोड़ने से पूर्व एआई-निर्मित प्रश्नों की जांच, संपादन एवं अनुमोदन करें।",
    uploadMaterialNow: "सामग्री अपलोड करें",
    openQuestionBank: "प्रश्न बैंक खोलें",
    dragDropManuals: "प्रशिक्षण नियमावली यहाँ खींचें और छोड़ें या ब्राउज़ करें",
    supportedFormats: "TXT, PDF, DOCX समर्थित (अधिकतम 20MB प्रति फ़ाइल)",
    presetManualsTitle: "अथवा आधिकारिक MoSPI प्रशिक्षण सामग्री चुनें:",
    customManualText: "अथवा सीधे नियमावली का अंश / पाठ यहाँ पेस्ट करें:",
    ingestAndGenerate: "सामग्री प्रविष्ट करें एवं प्रश्न निर्माण पर जाएं",
    mcqConfigTitle: "एआई प्रश्न निर्माण विन्यास",
    selectDomainPrompt: "लक्षित दक्षता डोमेन चुनें:",
    selectCompPrompt: "लक्षित दक्षता चुनें:",
    selectDifficultyPrompt: "कठिनाई स्तर चुनें:",
    selectQuestionCount: "प्रश्नों की संख्या चुनें:",
    foundationalDiff: "बुनियादी (स्तर 1-2)",
    intermediateDiff: "मध्यम (स्तर 3)",
    advancedDiff: "उन्नत (स्तर 4-5)",
    generateWithGemini: "जेमिनी इंटरैक्शन एपीआई द्वारा प्रश्न बनाएं",
    generatingMcqsWait: "जेमिनी एआई द्वारा आधिकारिक सांख्यिकी प्रश्न बनाए जा रहे हैं...",
    reviewTitle: "प्रशिक्षक मूल्यांकन मद समीक्षा एवं सत्यापन",
    reviewSubtitle: "एआई-निर्मित प्रश्नों का निरीक्षण करें, स्रोत नियमावली उद्धरणों का सत्यापन करें और प्रश्न बैंक हेतु अनुमोदित करें।",
    approveAll: "सभी सत्यापित प्रश्न स्वीकृत करें",
    approveSelected: "प्रश्न स्वीकृत करें",
    rejectSelected: "अस्वीकार / हटाएं",
    editQuestion: "प्रश्न सामग्री संपादित करें",
    questionStem: "प्रश्न का मुख्य भाग (Stem)",
    optionsLabel: "विकल्प",
    correctAnswerIndex: "सही उत्तर (सूचकांक)",
    explanationLabel: "सांख्यिकीय कार्यप्रणाली व्याख्या",
    sourceCitation: "स्रोत नियमावली उद्धरण",
    saveAndApprove: "सहेजें एवं प्रश्न बैंक में जोड़ें",
    questionBankTitle: "आधिकारिक मूल्यांकन भंडार एवं संवर्ग प्रश्न बैंक",
    questionBankSubtitle: "आधिकारिक प्रशिक्षण सामग्री से निर्मित एवं एनएसएसटीए प्रशिक्षकों द्वारा सत्यापित तकनीकी प्रश्न।",
    searchQuestionsPlaceholder: "प्रश्न, दक्षता, स्रोत नियमावली खोजें...",
    allDifficulties: "सभी कठिनाइयां",
    allDomains: "सभी डोमेन",
    exportJson: "जेएसओएन निर्यात",
    ingestNewMaterial: "नई सामग्री प्रविष्ट करें",
    noQuestionsFound: "कोई मूल्यांकन प्रश्न नहीं मिला",
    noQuestionsHint: "अपने खोज मानदंड बदलें या नए प्रश्न उत्पन्न करने हेतु प्रशिक्षण दस्तावेज़ अपलोड करें।",
    viewOptionsCitation: "विकल्प एवं स्रोत उद्धरण देखें →",
    learnerPerformanceTitle: "प्रशिक्षार्थी दक्षता एवं क्षमता निगरानी",
    learnerPerformanceSubtitle: "सभी नामांकित सांख्यिकी अधिकारियों की विस्तृत मनोवैज्ञानिक एवं तकनीकी प्रगति ट्रैकिंग।",
    enrolledOfficersList: "नामांकित सांख्यिकी अधिकारी (बैच 2024-26)",
    individualCadreDossier: "व्यक्तिगत संवर्ग डोजियर",
    domainProficiencyBreakdown: "डोमेन प्रवीणता विवरण",
    facultyRecommendedAction: "संकाय अनुशंसित कार्रवाई",
    facultyActionDesc: "शीर्ष प्राथमिकता अंतरालों को हल करने हेतु NSSTA AI Imputation मॉड्यूल और DPDP Act अनुपालन ट्रैक की सिफारिश की जाती है।",
    selectOfficerToInspect: "अधिकारी का डोजियर देखने के लिए सूची में से चयन करें।",

    // Officer Dashboard & Realtime Beacon Keys
    liveCadreBeacon: "सक्रिय संवर्ग वास्तविक-समय सिंक्रनाइज़ेशन",
    cadreBeaconDesc: "एनएसएसटीए अधीनस्थ सांख्यिकी सेवा दक्षता बेंचमार्क मैट्रिक्स (v2026.2) से सीधे जुड़ा हुआ।",
    simulationTitle: "संवर्ग मानक सिमुलेशन (What-If Analysis)",
    simulationDesc: "आगामी पदोन्नति चक्र हेतु आवश्यक क्षमता निर्माण का पूर्वानुमान लगाने के लिए मानक समायोजित करें:",
    targetStandard: "लक्ष्य मानक",
    promotionThreshold: "पदोन्नति सीमा (85%)",
    goodMorning: "शुभ प्रभात",
    goodAfternoon: "शुभ दोपहर",
    goodEvening: "शुभ संध्या",
    profileOverview: "आधिकारिक संवर्ग डोजियर एवं अपार दक्षता प्रोफाइल",

    // Step Navigator & MCQ Generator Keys
    step1UploadNav: "1. सामग्री अपलोड",
    step2GenerateNav: "2. एआई प्रश्न निर्माण",
    step3ReviewNav: "3. समीक्षा एवं सत्यापन",
    step2McqEngine: "चरण 2: एआई बहुविकल्पीय प्रश्न निर्माण इंजन",
    groundedAssessmentGen: "जेमिनी द्वारा नियमावली-आधारित मूल्यांकन प्रश्न निर्माण",
    strictlyGrounded: "से नियमावली-आधारित सटीक प्रश्न निर्माण",
    changeMaterial: "← सामग्री बदलें",
    generationParams: "प्रश्न निर्माण विन्यास",
    wordsParsed: "शब्द",
    charsParsed: "वर्ण प्रविष्ट",
    numQuestionsFormulate: "बनाए जाने वाले प्रश्नों की संख्या",
    rapidCheck: "5 प्रश्न (त्वरित जांच)",
    standardBatch: "10 प्रश्न (मानक बैच - अनुशंसित)",
    comprehensiveDiag: "15 प्रश्न (विस्तृत मूल्यांकन)",
    targetDomainHint: "लक्षित डोमेन संकेत",
    competencyAlignment: "दक्षता संरेखण",
    strictGroundingGuardrails: "सख्त नियमावली-आधारित एवं प्रामाणिक दिशानिर्देश",
    verifiableTextExcerpt: "प्रत्येक प्रश्न हेतु दस्तावेज़ से सत्यापन योग्य उद्धरण",
    zeroInventedFacts: "शून्य अप्रमाणित तथ्य / शून्य दोहराव",
    chunkingText: "दस्तावेज़ का विभाजन हो रहा है...",
    runningGeminiApi: "जेमिनी एआई इंटरैक्शन एपीआई चल रही है...",
    verifyingSourceExcerpts: "स्रोत उद्धरणों एवं जेएसओएन स्कीमा का सत्यापन...",
    generateQuestionsBtn: "जेमिनी द्वारा प्रश्न बनाएं",

    // Question Review Keys
    step3Review: "चरण 3: प्रशिक्षक समीक्षा एवं स्रोत सत्यापन",
    validateCurateTitle: "निर्मित बहुविकल्पीय प्रश्नों का सत्यापन एवं संपादन",
    trainingDocument: "प्रशिक्षण दस्तावेज़",
    sourceReviewAudit: "स्रोत उद्धरणों की समीक्षा करें और आधिकारिक प्रश्न बैंक हेतु स्वीकृत करें।",
    approveAllBtn: "सभी स्वीकृत करें",
    publishToBankBtn: "स्वीकृत प्रश्न बैंक में जोड़ें",
    savingWait: "सहेज रहे हैं...",
    successPublishedBank: "सफलतापूर्वक प्रश्न बैंक में प्रकाशित!",
    archivedInFirestore: "मूल्यांकन प्रश्न भंडार में संग्रहीत कर लिए गए हैं और संवर्ग मूल्यांकन हेतु उपलब्ध हैं।",
    ingestAnotherFile: "अन्य फ़ाइल अपलोड करें",
    totalGenerated: "कुल निर्मित प्रश्न",
    approved: "स्वीकृत",
    pending: "लंबित",
    rejected: "अस्वीकृत",
    allQuestions: "सभी प्रश्न",
    pendingReviewFilter: "समीक्षा हेतु शेष",
    approvedFilter: "स्वीकृत",
    rejectedFilter: "अस्वीकृत",
    questionNumber: "प्रश्न",
    editBtn: "संपादित करें",
    approveBtn: "स्वीकृत करें",
    rejectBtn: "अस्वीकार करें",
    sourceExcerptCitation: "स्रोत नियमावली उद्धरण (दस्तावेज़ से सटीक अंश)",
    officialExplanation: "आधिकारिक सांख्यिकीय व्याख्या",
    editAssessmentQuestion: "मूल्यांकन प्रश्न संपादित करें",
    questionText: "प्रश्न पाठ",
    optionsSelectRadio: "विकल्प (सही उत्तर हेतु रेडियो बटन चुनें)",
    difficulty: "कठिनाई",
    saveMarkEdited: "सहेजें एवं संपादित चिह्नित करें",

    // Assessment Page Keys
    latestCompletedDiag: "नवीनतम पूर्ण मूल्यांकन",
    score: "स्कोर",
    of: "में से",
    correct: "सही",
    completedOn: "पूर्ण किया गया:",
    printPdfReport: "पीडीएफ रिपोर्ट प्रिंट करें",
    viewFullBreakdown: "विस्तृत विवरण देखें",
    officialCertInstrument: "आधिकारिक प्रमाणीकरण साधन",
    mospiNsstaStandard: "MoSPI / NSSTA मानकीकृत विनिर्देश",
    nationalCadreDiagEngine: "राष्ट्रीय सांख्यिकी संवर्ग दक्षता मूल्यांकन इंजन",
    deterministicBenchmarking: "सांख्यिकीय, तकनीकी, डिजिटल शासन और व्यवहार डोमेन में सटीक मनोवैज्ञानिक बेंचमार्किंग।",
    minutes: "मिनट",
    questions: "प्रश्न",
    dimensionsEvaluated: "इस मूल्यांकन में जांची जाने वाली 11 दक्षताएँ",

    // Actions & Common
    printReport: "प्रिंट / पीडीएफ सहेजें",
    exportReport: "आधिकारिक मूल्यांकन रिपोर्ट डाउनलोड करें (पीडीएफ)",
    retakeDiagnostic: "पुनः मूल्यांकन दें",
    viewSkillGaps: "अद्यतन कौशल अंतराल देखें",
    exploreCourses: "अनुशंसित पाठ्यक्रम देखें",
    startDiagnostic: "22-प्रश्नों का मूल्यांकन प्रारंभ करें",
    send: "भेजें",
    retry: "पुनः प्रयास करें",
    editProfile: "प्रोफाइल संपादित करें",
    saveChanges: "परिवर्तन सहेजें",
    cancel: "रद्द करें",
    listening: "सुन रहे हैं... अपना सांख्यिकीय प्रश्न बोलें",
    speakQuery: "बोलकर पूछें (आवाज़ से लिखें)",
    stopListening: "रोकें"
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    try {
      return localStorage.getItem("statskill_language") || "en";
    } catch {
      return "en";
    }
  });

  useEffect(() => {
    try {
      localStorage.setItem("statskill_language", language);
      document.documentElement.lang = language;
    } catch (e) {
      console.warn("Could not persist language to localStorage:", e);
    }
  }, [language]);

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === "en" ? "hi" : "en"));
  };

  const t = (key, fallback = "") => {
    if (!key) return fallback;
    const langDict = translations[language] || translations.en;
    if (langDict[key] !== undefined) return langDict[key];
    const enDict = translations.en;
    if (enDict[key] !== undefined) return enDict[key];
    return fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
